---
title: "Predicting graded dishabituation via perceptual stimulus embeddings in a rational learning model"
bibliography: library.bib
csl: apa6.csl
document-params: "10pt, letterpaper"

author-information: > 
    \author{{\large \bf Morton Ann Gernsbacher (MAG@Macc.Wisc.Edu)} \\ Department of Psychology, 1202 W. Johnson Street \\ Madison, WI 53706 USA
    \AND {\large \bf Sharon J.~Derry (SDJ@Macc.Wisc.Edu)} \\ Department of Educational Psychology, 1025 W. Johnson Street \\ Madison, WI 53706 USA}

abstract: >
   How do humans decide what to look at and when to stop looking? Many computational models have been proposed to address the mechanisms underlying such processes, but they are all limited in scope. In this paper, we present a version of the rational action, noisy choice for habituation (RANCH) model with an instantiated perceptual encoding hypothesis. We showed that the model can not only capture key looking time patterns such as habituation and dishabituation, but also make more fine grained predictions about dishabituation magnitude. We also investigated the generalizability and robustness of the RANCH parameters. In addition, we evaluated whether the assumptions in the model are critical. We found that RANCH’s performance is relatively robust across parameters, and the parameters can be generalized to other tasks. However, the assumptions about the perceptual encoding process, the learning process and the decision process are critical for the model performance. 

    
keywords: >
    Add your choice of indexing terms or keywords; kindly use a semi-colon; between each term.
    
output: cogsci2016::cogsci_paper
#final-submission: \cogscifinalcopy
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=3, fig.height=3, fig.crop = F, 
                      fig.pos = "tb", fig.path='figs/',
                      echo=F, warning=F, cache=F, 
                      message=F, sanitize = T)
```

```{r, libraries}
library(png)
library(here)
library(tidyverse)
library(grid)
library(ggplot2)
library(xtable)
```



# Introduction 


```{r child = "01_intro.Rmd"}
```


# Behavioral Experiment   


```{r child = "02_behavioral_exp.Rmd"}
```

# Model  

```{r child = "03_model_spec.Rmd"}
```

# Model Evaluation 

```{r child = "04_model_fits.Rmd"}
```

# Discussion

```{r child = "05_discussion.Rmd"}
```



# References 

```{r}
# References will be generated automatically by Pandoc and included here.
# The following code is some latex to format the bibliography. Do not remove it.
```

\setlength{\parindent}{-0.1in} 
\setlength{\leftskip}{0.125in}
\noindent
