The experimental paradigm is modeled after the behavioral experiment described in CITE. In previous work, this paradigm has successfully captured habituation and dishabituation in adults.  


```{r design_fig, fig.env = "figure", fig.pos = "H", fig.align='center', fig.width=3.5, fig.height=3.5, set.cap.width=T, num.cols.cap=1, fig.cap = "Experimental design of behavioral task: Adults watched sequences of stimuli consisting a familiarization to a stimulus (left), following by one of five trial types, which violates one property of the familiar stimulus: In the violation trials, participants saw either (1) the same exact stimulus (Background), (2) the same stimulus in a different orientation (Pose), (3) the same stimulus, but duplicated (or single if it was already duplicated; Number), (4) a different stimulus but in the same animacy class (Identity), or (5) a different stimulus of the opposite animacy (Animacy)."}
img <- png::readPNG("figs/lab_logo_stanford.png")
grid::grid.raster(img)
```

## Methods

### Stimuli

All stimuli were created using images selected from Unity assets Quirky Series - Animals (LINK) and 3D Prop Vegetables and Fruits (LINK) with added shaking animation. For each image from the animal set, we created a mirrored version to create an image with a different pose. Since most stimuli from the vegetable set are symmetrical, the images were slightly tilted before the mirroring. 


### Procedure 

The experiment was a web-based self-paced experiment that consisted of two phases. In the first phase, participants saw 24 blocks that consisted of either two, four, or six trials. On each trial, a schematic screen would rise up to reveal a stimulus behind it. Participants pressed the spacebar to go on to the next trial after a minimum viewing time of 500 ms, triggering the schematic screen to drop and raise again to reveal the next stimulus. 

Each participant saw eight types of repeating stimuli. The eight types of stimuli include all combinations of the three features that each include two levels: animacy (e.g. animate or inanimate), number (singleton or pair), and pose (facing left or right). 

8 blocks consisted of one stimulus being repeatedly presented throughout the block (i.e. background trials). The remaining 16 blocks included two stimuli, including one that was repeatedly present and one that deviated from the trial. The deviant trial was always different from the repeating stimulus in one of the four dimensions: animacy violation, identity violation, number violation, and pose violation. The deviant trial always showed up in the last trial of the block. In the first three violation types, the feature would be switched to the previously unseen level (e.g. an inanimate deviant after an animate repeating stimulus, keeping the number and the pose the same). For identity violation, the participants would see a different, but within-category, exemplar from the repeating stimuli type. Among the sixteen blocks, the four violation type each appeared four times. After each block, participants performed a simple memory task as a filler task. 

The order of the block was semi-randomized. To control for the distribution of background blocks and deviant blocks, we group the twenty-four blocks into four groups. Each group consisted of two background blocks, and one deviant block from each violation type. The order of blocks within each group was randomized.


### Participants 

The final sample included XXX participants recruited from Prolific(Mean Age: SD:). Participants were excluded if either (1) the standard deviation of log-transformed of their reaction times on all trials is less than 0.15 (indicating key-smashing); (2) spent more than three absolute deviations above the median of the task completion time as reported by Prolific, or (3) provided the incorrect response to more than 20% of the memory task. After the participant-level exclusion, we also applied trial-level exclusion. A trial was excluded from final analysis if it is three absolute deviations away from the median in the log-transformed space across all participants. 

## Results

The sample size and analysis plan are all pre-registered and can be found here [LINK]. All experimental materials are publicly available and can be found here [LINK].

We were primarily interested in (1) whether our experimental paradigm captured habituation and dishabituation and (2) whether the magnitude of dishabituation was influenced by the type of violation.  We tested these two hypotheses in a linear mixed-effect model with maximal random effect structure that predicts log-transformed looking time with the following specification:  log(total_rt) ~ trial_number +  is_first_trial +  (trial_number + is_first_trial) * number + (trial_number + is_first_trial) * pose +(trial_number + is_first_trial) * animacy + (trial_number + is_first_trial) * trial_type. The combination of trial_number and is_first_trial models habituation. 


 interaction between trial number number and whether the trial is the first trial models the habituation effect, testing the first hypothesis. The following three interactions investigates whether the feature of background trials would have an impact on the looking time. The last interaction term, with trial type having five levels (background trial or four types of violation), aims to test the second hypothesis. The model with maximum random effect structure failed to converge, so we pruned the model following the pre-registered procedure. The final model included per-subject random intercepts.

There was also some evidence that participants showed graded dishabituation to different types of violation. Animacy violation was significantly greater than the number violation (STATS) as well as the number violation (STATS). We also pre-registered a qualitative prediction on the ordering of the dishabituation magnitude (i.e. category > number > identity > pose). However, we did not find evidence consistent with this prediction. The qualitative ordering in our data was animacy (M, SD), identity (M, SD), pose (M, SD) and number (M, SD). 




