
```{r}
library(tidyverse)
library(here)
library(colf)
library(Metrics)


source(here("analysis/helper/summarize_behavioral_data.R"))

raw_d <- read_csv(here("data/behavioral_data/behavioral_d.csv"))

bd <- read_csv(here("data/behavioral_data/bd_fit.csv"))
sd <- read_csv(here("data/model_sim_data/eig_summarised.csv"))
```

# Plain 

```{r}



run_k_fold <- function(p_id, raw_bd, sd){
  
  # get all the subjects 
  all_sbj <- unique(raw_d$prolific_id)
  n_folds = 10

  # currently testing on one set of parameter 
  rsquared <- vector(mode = "list", length = n_folds)
  rmse <- vector(mode = "list", length = n_folds)

  for (k in 1:n_folds){

  # separate the data in to train & test
    train_subject = sample(all_sbj, floor(length(all_sbj) * .9))
    train_data = summarize_behavioral_data(raw_d %>% filter(prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>% ungroup())
    test_data = summarize_behavioral_data(raw_d %>% filter(!prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>% ungroup())
  
  # fit the training set, currently excluding the block_number 
    fitted_stats = colf_nlxb(mean_lt ~ mean_sample, data = train_data, lower = c(-Inf, 0))
    sample_slope = fitted_stats$coefficients["param_mean_sample"]
    sample_intercept = fitted_stats$coefficients["param_X.Intercept."]

    test_scaled <- test_data %>% 
      mutate(scaled_samples = mean_sample * sample_slope  + sample_intercept)
  
  # save results for each fold 
    rsquared[[k]] <- cor(test_scaled$mean_lt, test_scaled$scaled_samples)^2
    rmse[[k]] <- rmse(test_scaled$mean_lt, test_scaled$scaled_samples)
  
  }

  rsquared_average <- mean(unlist(rsquared))
  rmse_average <- mean(unlist(rmse))
  
  return(
    tibble(
      "param_id" = p_id, 
      "mean_rsquared" = rsquared_average, 
      "mean_rmse" = rmse_average
    )
  )
  
}


full_k_fold_res <- lapply(
  unique(sd$param_id), 
  function(id){
    run_k_fold(p_id = id, raw_bd = raw_d, sd = sd)
  }
) %>% 
  bind_rows()
```

```{r}
full_k_fold_res %>% 
  ggplot(aes(x = mean_rsquared)) + 
  geom_histogram(bins = 40)

full_k_fold_res %>% 
  ggplot(aes(x = mean_rmse)) + 
  geom_histogram(bins = 40)


```





```{r}
test_scaled %>% 
  pivot_longer(cols = c("mean_lt", "scaled_samples"), names_to = "type", values_to = "val") %>% 
  ggplot(aes(x = trial_number, y = val, color = trial_type)) + 
  geom_point() + 
  geom_line(aes(group = trial_type))+
  facet_wrap( ~type, scales = "free")

test_scaled %>% 
  pivot_longer(cols = c("mean_lt", "scaled_samples"), names_to = "type", values_to = "val") %>% 
  ggplot(aes(x = trial_type, y = val, color = type)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2))
```


# Plain with block_id 

```{r}



run_k_fold <- function(p_id, raw_bd, sd){
  
  # get all the subjects 
  all_sbj <- unique(raw_d$prolific_id)
  n_folds = 10

  # currently testing on one set of parameter 
  rsquared <- vector(mode = "list", length = n_folds)
  rmse <- vector(mode = "list", length = n_folds)

  for (k in 1:n_folds){

  # separate the data in to train & test
    train_subject = sample(all_sbj, floor(length(all_sbj) * .9))
    train_data = summarize_behavioral_data_with_block(raw_d %>% filter(prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>% ungroup())
    test_data = summarize_behavioral_data_with_block(raw_d %>% filter(!prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>% ungroup())
  
  # fit the training set, currently excluding the block_number 
    fitted_stats = colf_nlxb(mean_lt ~ mean_sample + block_number, data = train_data, lower = c(-Inf, 0, -Inf))
    sample_slope = fitted_stats$coefficients["param_mean_sample"]
    sample_intercept = fitted_stats$coefficients["param_X.Intercept."]
    block_slope = fitted_stats$coefficients["param_block_number"]

    test_scaled <- test_data %>% 
      mutate(scaled_samples = mean_sample * sample_slope + block_number * block_slope + sample_intercept)
  
  # save results for each fold 
    rsquared[[k]] <- cor(test_scaled$mean_lt, test_scaled$scaled_samples)^2
    rmse[[k]] <- rmse(test_scaled$mean_lt, test_scaled$scaled_samples)
  
  }

  rsquared_average <- mean(unlist(rsquared))
  rmse_average <- mean(unlist(rmse))
  
  return(
    tibble(
      "param_id" = p_id, 
      "mean_rsquared" = rsquared_average, 
      "mean_rmse" = rmse_average
    )
  )
  
}


full_k_fold_res <- lapply(
  unique(sd$param_id), 
  function(id){
    run_k_fold(p_id = id, raw_bd = raw_d, sd = sd)
  }
) %>% 
  bind_rows()

```


```{r}
full_k_fold_res %>% 
  ggplot(aes(x = mean_rsquared)) + 
  geom_histogram(bins = 40)

full_k_fold_res %>% 
  ggplot(aes(x = mean_rmse)) + 
  geom_histogram(bins = 40)

```

# try with the full dataset


```{r}
full_ds <- bd %>% 
  left_join(sd %>% filter(param_id == 60), by = c("trial_number", "trial_type"))

fitted_stats = colf_nlxb(mean_lt ~ mean_sample, data = full_ds, lower = c(-Inf, 0))
sample_slope = fitted_stats$coefficients["param_mean_sample"]
sample_intercept = fitted_stats$coefficients["param_X.Intercept."]
  
test_scaled <- full_ds %>% 
      mutate(scaled_samples = mean_sample * sample_slope + sample_intercept)
  
  # save results for each fold 
rsquare <- cor(test_scaled$mean_lt, test_scaled$scaled_samples)^2
rmse<- rmse(test_scaled$mean_lt, test_scaled$scaled_samples)

test_scaled %>% 
  pivot_longer(cols = c("mean_lt", "scaled_samples"), names_to = "type", values_to = "val") %>% 
  ggplot(aes(x = trial_number, y = val, color = trial_type)) + 
  geom_point() + 
  geom_line(aes(group = trial_type))+
  facet_wrap( ~type, scales = "free")

test_scaled %>% 
  pivot_longer(cols = c("mean_lt", "scaled_samples"), names_to = "type", values_to = "val") %>% 
  ggplot(aes(x = trial_type, y = val, color = type)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2))
```


# what if we fit the habituation & graded dishabituation separately? 

## hab dishab 

```{r}
raw_d <- read_csv(here("data/behavioral_data/behavioral_d.csv"))
eig_hab_dishab <- read_csv(here("data/model_sim_data/eig_hab_dishab.csv"))

run_k_fold <- function(p_id, raw_bd, sd){
  
  # get all the subjects 
  all_sbj <- unique(raw_d$prolific_id)
  n_folds = 10

  # currently testing on one set of parameter 
  rsquared <- vector(mode = "list", length = n_folds)
  rmse <- vector(mode = "list", length = n_folds)

  for (k in 1:n_folds){

  # separate the data in to train & test
    train_subject = sample(all_sbj, floor(length(all_sbj) * .9))
    train_data = summarize_hab_dishab(raw_d %>% filter(prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>%  ungroup())
    test_data = summarize_hab_dishab(raw_d %>% filter(!prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>%  ungroup())
  
  # fit the training set, currently excluding the block_number 
    fitted_stats = colf_nlxb(mean_lt ~ mean_sample, data = train_data, lower = c(-Inf, 0))
    sample_slope = fitted_stats$coefficients["param_mean_sample"]
    sample_intercept = fitted_stats$coefficients["param_X.Intercept."]

    test_scaled <- test_data %>% 
      mutate(scaled_samples = mean_sample * sample_slope  + sample_intercept)
  
  # save results for each fold 
    rsquared[[k]] <- cor(test_scaled$mean_lt, test_scaled$scaled_samples)^2
    rmse[[k]] <- rmse(test_scaled$mean_lt, test_scaled$scaled_samples)
    print(param_id)
  }

  rsquared_average <- mean(unlist(rsquared))
  rmse_average <- mean(unlist(rmse))
  
  
  return(
    tibble(
      "param_id" = param_id, 
      "mean_rsquared" = rsquared_average, 
      "mean_rmse" = rmse_average
    )
  )
  
}

full_k_fold_res <- lapply(
  unique(eig_hab_dishab$param_id), 
  function(id){
    run_k_fold(id, raw_bd = raw_d, sd = eig_hab_dishab)
  }
) %>% 
  bind_rows()


```


```{r}
full_k_fold_res %>% 
  ggplot(aes(x = mean_rsquared)) + 
  geom_histogram(bins = 40)

full_k_fold_res %>% 
  ggplot(aes(x = mean_rmse)) + 
  geom_histogram(bins = 40)

```

```{r}
test_scaled %>% 
  filter(param_id == 50) %>% 
  ggplot(aes(x = trial_number, y = val, color = trial_type)) + 
  geom_point() + 
  geom_line(aes(group = trial_type))+
  facet_grid(block_number~type, scales = "free")
```

## deviant only 

```{r}
raw_d <- read_csv(here("data/behavioral_data/behavioral_d.csv"))
eig_dev <- read_csv(here("data/model_sim_data/eig_deviant_only.csv"))

run_k_fold <- function(p_id, raw_bd, sd){
  
  # get all the subjects 
  all_sbj <- unique(raw_d$prolific_id)
  n_folds = 10

  # currently testing on one set of parameter 
  rsquared <- vector(mode = "list", length = n_folds)
  rmse <- vector(mode = "list", length = n_folds)

  for (k in 1:n_folds){

  # separate the data in to train & test
    train_subject = sample(all_sbj, floor(length(all_sbj) * .9))
    train_data = summarize_dev_only(raw_d %>% filter(prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>% ungroup())
    test_data = summarize_dev_only(raw_d %>% filter(!prolific_id %in% train_subject)) %>% ungroup() %>% left_join(sd %>% filter(param_id == p_id) %>% ungroup())
  
  # fit the training set, currently excluding the block_number 
    fitted_stats = colf_nlxb(mean_lt ~ mean_sample, data = train_data, lower = c(-Inf, 0.0000001))
    sample_slope = fitted_stats$coefficients["param_mean_sample"]
    sample_intercept = fitted_stats$coefficients["param_X.Intercept."]

    test_scaled <- test_data %>% 
      mutate(scaled_samples = mean_sample * sample_slope  + sample_intercept)
  
  # save results for each fold 
    rsquared[[k]] <- cor(test_scaled$mean_lt, test_scaled$scaled_samples)^2
    rmse[[k]] <- rmse(test_scaled$mean_lt, test_scaled$scaled_samples)
  }

  rsquared_average <- mean(unlist(rsquared))
  rmse_average <- mean(unlist(rmse))
  
  
  return(
    tibble(
      "param_id" = p_id, 
      "mean_rsquared" = rsquared_average, 
      "mean_rmse" = rmse_average
    )
  )
  
}

full_k_fold_res <- lapply(
  unique(eig_dev$param_id), 
  function(x){
    run_k_fold(p_id = x, raw_bd = raw_d, sd = eig_dev)
  }
) %>% 
  bind_rows()
```


```{r}
test_scaled %>% 
   pivot_longer(cols = c("mean_lt", "scaled_samples"), names_to = "type", values_to = "val") %>% 
  ggplot(aes(x = trial_type, y = val, color = type)) + 
  geom_point()
```

# Simulation results 

```{r}
sd %>% 
   filter(trial_type != "background") %>% 
  group_by(param_id, trial_type) %>% 
  summarise(mean_sample  = mean(mean_sample)) %>% 
  ggplot(aes(x = trial_type, y = mean_sample, color = trial_type)) + 
  geom_line(aes(group = param_id), alpha = .3) + 
  #geom_point(position = position_dodge(width  = .2), alpha = .3) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2))
```

```{r}
raw_d %>% 
  filter(!is.na(val)) %>% 
  ggplot(aes(x = violation_type, y = val)) + 
  stat_summary(fun.data = "mean_cl_boot") 
```

```{r}
sd %>% 
  mutate(trial_type_overall = if_else(trial_type == "background", "background", "deviant")) %>% 
  ggplot(aes(x = trial_number, y = mean_sample, color = trial_type_overall)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2)) 
  
```

